/**
 * Writes js/config.generated.js for the browser.
 * Set SHEETS_API_KEY in the environment (e.g. Vercel), or create a one-line .sheets-key file in the project root (gitignored).
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
let key = process.env.SHEETS_API_KEY || "";
const keyFile = path.join(root, ".sheets-key");
try {
  if (!key && fs.existsSync(keyFile)) {
    key = fs.readFileSync(keyFile, "utf8").trim();
  }
} catch {
  /* ignore */
}

const out =
  "// Generated by npm run build — do not edit by hand\n" +
  "window.__SHEETS_API_KEY__ = " +
  JSON.stringify(key) +
  ";\n";

fs.writeFileSync(path.join(root, "js", "config.generated.js"), out, "utf8");
console.log("Wrote js/config.generated.js (" + (key ? "key present" : "empty key — set SHEETS_API_KEY or .sheets-key") + ")");
